name: spark
version: 0.0.3-dev
author: Chrome Team <apps-dev@chromium.org>
description: A Chrome app based development environment.
homepage: https://github.com/GoogleChrome/spark
dependencies:
  ace: '>=0.0.8'
  analyzer: any
  browser: any
  chrome_gen: '>=0.0.8'
  intl: any
  logging: any
  mime: any
  polymer: any
dev_dependencies:
  args: any
  grinder: 0.0.7
  unittest: any
