name: spark
version: 0.0.3-dev
author: Chrome Team <apps-dev@chromium.org>
description: A Chrome app based development environment.
homepage: https://github.com/GoogleChrome/spark
dependencies:
  ace:
    path: ../../ace.dart
  analyzer: any
  bootjack: any
  browser: any
  chrome_gen: '>=0.1.0'
  crc32: 0.1.3
  crypto: any
  intl: any
  logging: any
  mime: any
  spark_widgets:
    path: ../widgets
dev_dependencies:
  args: any
  grinder: any
  unittest: any
