name: spark.widgets
version: 0.0.1-dev
author: Chrome Team <apps-dev@chromium.org>
description: GUI widget library for Spark IDE and applications built with it.
homepage: https://github.com/GoogleChrome/spark
dependencies:
  polymer: any
