name: cde_core
version: 0.0.1-dev
description: Low-level, core functionality for the Chrome Dev Editor (CDE).
homepage: https://github.com/dart-lang/spark/
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  unittest: any
